#!/bin/bash

# This script cleans up all Probe custom resources generated by the k6 load testing suite.

echo "🧹 Cleaning up k6 load test Probes..."
kubectl delete probes -l created-by=k6-load-test --all-namespaces

if [ $? -eq 0 ]; then
    echo "✅ Cleanup complete!"
else
    echo "❌ Cleanup encountered an error or no probes were found."
fi
